---
# YAML documents begin with the document separator ---
# The minus in YAML this indicates a list item. The Playbook contains a list
# of plays, with each play being a dictionary

- 
  # Target: where our play will run and options it will run with
  hosts: all

  # Task: the list of tasks that will be executed within the playbook
  tasks:       
     - name: A block of modules being executed 
       block:
         - name: Example 1 Oracle only
           debug:
             msg: Example 1 Oracle only
           when: ansible_distribution == "OracleLinux"
         - name: Example 2 Ubuntu only
           debug:
             msg: Example 2 Ubuntu only
           when: ansible_distribution == "Ubuntu"
         - name: Example 3
           debug:
             msg: "Example 3 with items - {{ item }}"
           with_items: ['x','y','z']
# Three dots indicate the end of a YAML document
...
